trigger_url: <url to send the trigger request to>
trigger_token: <token>
github_token: <token>

repositories:
  repository-name:
    name: org/name
    gitlab_url: https://<gitlab-url>
    gitlab_token: <token>
    slack-webhook-url: <slack webhook url to post job status>
